services:
  - type: web
    name: exammentor-backend
    env: python
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: SCIPY_OPENBLAS_NO_GNU_SECTION
        value: 1
      - key: PYTHON_VERSION
        value: 3.11.0
